title: Andujar Brutus' Portfolio
description: > # this means to ignore newlines until "baseurl:"
  view my work
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
#url: "https://brutusa.github.io" # the base hostname & protocol for your site, e.g. http://example.com
url: "https://andujarbrutus.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Andujar Brutus # add your name
author-img: andujar-brutus.png # add your photo
about-author: Motivated Computer Science senior with web development experience, interested in expanding to software development, data
  science, or machine learning engineering roles. Driven to apply both technical expertise and interpersonal skills to deliver
  impactful solutions. # add description
social-twitter:  # add your Twitter handle
social-facebook: andujar.brutus # add your Facebook handle
social-github: brutusa # add your Github handle
social-linkedin: abrutus # add your Linkedin handle
social-email: andujarbrutus@gmail.com # add your Email address
social-resume: https://drive.google.com/file/d/1c4Eb_PTUk6b_UhcV_E7eRTLkkIsO_jBB/view # add your resume

# Disqus
discus-identifier:  # add your discus identifier

# Tracker
analytics: G-W10V6F865Z

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

